name: CI Pipeline

on:
    push:
        branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v4
              with: 
                go-version: '1.24'

            - name: Install dependencies
              run: go mod download

            - name: Run tests
              run: go test ./...

            - name: Build
              run: go build -o ci_pipline ./cmd/main.go
